services:
  db:
    image: postgres:latest
    container_name: calendar
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/calendar
    ports:
      - "5432:5432"

volumes:
  postgres_data: